// Matches database/seeds/02_rd_provinces_seed.sql.
const dominicanProvinces = <String>[
  'Distrito Nacional',
  'Santo Domingo',
  'Santiago',
  'La Vega',
  'San Cristóbal',
  'Puerto Plata',
  'La Altagracia',
  'San Pedro de Macorís',
  'Duarte',
  'La Romana',
  'Espaillat',
  'San Juan',
  'Peravia',
  'Barahona',
  'Azua',
  'Monseñor Nouel',
  'Monte Plata',
  'Sánchez Ramírez',
  'María Trinidad Sánchez',
  'Valverde',
  'Hato Mayor',
  'Monte Cristi',
  'Samaná',
  'Bahoruco',
  'Hermanas Mirabal',
  'El Seibo',
  'San José de Ocoa',
  'Dajabón',
  'Santiago Rodríguez',
  'Elías Piña',
  'Independencia',
  'Pedernales',
];
