name: rdreporta
description: "Plataforma de información ciudadana y reportes geolocalizados de República Dominicana"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking & Storage
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  
  # Maps & Location
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.1
  geocoding: ^5.0.0
  
  # Media & UI
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^8.2.0
  video_player: ^2.14.1
  visibility_detector: ^0.4.0+2
  video_compress: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/google_g.png
    - assets/branding/rdreporta_logo_dark.png
    - assets/branding/rdreporta_logo_light.png
    - assets/branding/rdreporta_dark_flutter.svg
    - assets/branding/rdreporta_light_flutter.svg
    - assets/emojis/
